name: gradle_repo_manager
description: simple CLI application that adds a repo to all *.gradle files in sub dirs
version: 2.2.1+0
repository: https://github.com/FMotalleb/gradle_repo_manager
# homepage: https://www.example.com
executables:
  repo: gradle_repo_manager
environment:
  sdk: ">=2.18.2 <3.0.0"

dependencies:
  args: ^2.3.1
  cli_util: ">=0.3.5 <0.5.0"
  path: ^1.8.0

dev_dependencies:
  lints: ^2.0.0
  test: ^1.16.0
